#!/bin/bash

source /var/onap/asserts
source /var/onap/mr

covered_functions=(
"init_mr"
)

# test_init_mr() - Verify the built and start of Message Router services
function test_init_mr {
    init_mr

    asserts_image dockerfiles_kafka
    asserts_image anapsix/alpine-java
    asserts_image attos/dmaap
    asserts_image wurstmeister/zookeeper
}

for func in ${covered_functions[@]}; do
    test_$func
    echo "test_$func passed.."
done
