#!/bin/bash

source /var/onap_tests/_test_base
source /var/onap/integration

covered_functions=(
"clone_integration_repos"
)

# test_clone_integration_repos() - Verify that Integration repositories are cloned properly
function test_clone_integration_repos {
    clone_repos "integration"

    asserts_file_exist ${src_folders[integration]}/README.md
    asserts_file_exist ${src_folders[integration]}/devtool/LICENSE
    #asserts_file_exist ${src_folders[integration]}/seccom/
}

if [ "$1" != '*' ]; then
    unset covered_functions
    covered_functions=$1
fi
main "${covered_functions[@]}"
