#!/bin/bash

set -o xtrace

# pull_hbase_docker_image() - Pull HBase container image from a Docker Registry Hub
function pull_hbase_docker_image {
    local hbase_version=${1:-1.2.3}
    docker login -u $nexus_username -p $nexus_password $nexus_docker_repo
    docker pull $nexus_docker_repo/aaidocker/aai-hbase-${hbase_version}
    docker rm -f hbase-1.2.3
    docker run -d --net=host --name="hbase-1.2.3" aaidocker/aai-hbase-${hbase_version}
}

# install_aai_service() - Install AAI Service from source code
function install_aai_service {
    if [ ! -d /opt/aai/src/aai-service ]; then
        git clone https://git.onap.org/aai/aai-service /opt/aai/src/aai-service
    fi
    pushd /opt/aai/src/aai-service
    mvn -N -P runAjsc
    popd
}

# install_ajsc() - Install ASJC Java service container
function install_ajsc {
    docker login -u $nexus_username -p $nexus_password $nexus_docker_repo
    docker pull $nexus_docker_repo/openecomp/ajsc-aai:$docker_version
    docker rm -f aai-service
    docker run --name=aai-service --net=host -v /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt -it -e AAI_REPO_PATH=r/aai -e AAI_CHEF_ENV=simpledemo -d -e AAI_CHEF_LOC=/var/chef/aai-data/environments -e docker_gitbranch=master $nexus_docker_repo/openecomp/ajsc-aai:$docker_version
}


# install_model_loader() Install Model Loader 
function install_model_loader {
    if [ ! -d /opt/aai/src/model-loader ]; then
      git clone https://git.onap.org/aai/model-loader /opt/aai/src/model-loader
    fi
    pushd /opt/aai/src/model-loader
    mvn clean package docker:build
    cat <<EOL > /etc/model-loader.conf
DISTR_CLIENT_ASDC_ADDRESS=${SDC_ADDRESS:-localhost}
DISTR_CLIENT_CONSUMER_GROUP=${UEB_CONSUMER_GROUP:-SDCGroup}
DISTR_CLIENT_CONSUMER_ID=${UEB_CONSUMER_GROUP_ID:-UEB}
DISTR_CLIENT_ENVIRONMENT_NAME=${ENVIRONMENT_NAME:-Env}
DISTR_CLIENT_PASSWORD=${SDC_PASSWORD:-password}
DISTR_CLIENT_USER=${SDC_USER:-SDCUser}
                     
APP_SERVER_BASE_URL=${APP_SERVER_URL:-https://localhost:8443}
APP_SERVER_AUTH_USER=${APP_USER:-AppUser}
APP_SERVER_AUTH_PASSWORD=${APP_PASSWORD:-password}
EOL
    docker run --env-file /etc/model-loader.conf model-loader
    popd
}

# init_aai() - Function that initialize AAI services
function init_aai {
    mkdir -p /opt/openecomp/aai/logs
    mkdir -p /opt/openecomp/aai/data

    pull_hbase_docker_image
    install_aai_service

    # Wait 3 minutes before instantiating the A&AI container
    sleep 180

    install_ajsc
    install_model_loader
}

