#!/bin/bash

set -o xtrace

# is_package_installed() - Function to tell if a package is installed
function is_package_installed {
    if [[ -z "$@" ]]; then
        return 1
    fi
    dpkg -s "$@" > /dev/null 2> /dev/null
}

# install_package() - Install specific package if doesn't exist
function install_package {
    local package=$1
    if ! is_package_installed $package; then
        apt-get update -y
        apt-get install -y $package
    fi
}
