#!/bin/bash

set -o xtrace

source /var/onap/asserts

# install_message_router() - Downloads and configure message router source code
function install_message_router {
    local src_folder=/opt/dcae/message-router
    clone_repo dcae/demo/startup/message-router $src_folder
    pushd $src_folder
    is_package_installed docker-ce || install_docker
    bash deploy.sh
    asserts_image wurstmeister/zookeeper
    # Cannot assert for kafka since docker-compose generates a default name when building image
    asserts_image attos/dmaap
    popd
}

# init_mr() - Function that initialize Message Router services
function init_mr {
    install_message_router
}
