#!/bin/bash

set -o xtrace

# pull_sdnc() - Pull SDNC docker image
function pull_sdnc {
    docker login -u $nexus_username -p $nexus_password $nexus_docker_repo

    docker pull $nexus_docker_repo/openecomp/sdnc-image:$docker_version
    docker tag $nexus_docker_repo/openecomp/sdnc-image:$docker_version openecomp/sdnc-image:latest
}

# pull_admportal_sdn() - Pull SDNC docker image
function pull_admportal_sdnc {
    docker login -u $nexus_username -p $nexus_password $nexus_docker_repo

    docker pull $nexus_docker_repo/openecomp/admportal-sdnc-image:$docker_version
    docker tag $nexus_docker_repo/openecomp/admportal-sdnc-image:$docker_version openecomp/admportal-sdnc-image:latest
}

# pull_dgbuilder_sdnc() - Pull SDNC docker image
function pull_dgbuilder_sdnc {
    docker login -u $nexus_username -p $nexus_password $nexus_docker_repo

    docker pull $nexus_docker_repo/openecomp/dgbuilder-sdnc-image:$docker_version
    docker tag $nexus_docker_repo/openecomp/dgbuilder-sdnc-image:$docker_version openecomp/dgbuilder-sdnc-image:latest
}

# install_sdnc() -  Download and install SDNC services from source code
function install_sdnc {
    if [ ! -d /opt/sdnc ]; then
        git clone -b $gerrit_branch --single-branch http://gerrit.onap.org/r/sdnc/oam.git /opt/sdnc
    fi
    pushd /opt/sdnc
    /opt/docker/docker-compose up -d
    popd
}

# init_sdnc() - Function that initialize SDNC services
function init_sdnc {
    pull_sdnc
    pull_admportal_sdnc
    pull_dgbuilder_sdnc
    install_sdnc
}
