#!/bin/bash

set -o xtrace

source /var/onap/asserts

# clone_all_sdnc_repos() - Function that clones SDNC source repo.
function clone_all_sdnc_repos {
    local src_folder=/opt/openecomp/sdnc

    for dirc in adaptors core northbound oam plugins; do
        clone_repo sdnc/$dirc $src_folder/$dirc
    done
}

# compile_all_sdnc_repos() - Function that compiles SDNC source repo.
function compile_all_sdnc_repos {
    local src_folder=/opt/openecomp/sdnc

    for dirc in adaptors core northbound oam plugins; do
        if [[ "$dirc" == "core" ]]; then
                compile_src $src_folder/$dirc/rootpom
        fi
        compile_src $src_folder/$dirc
    done
}

# build_sdnc_images() - Builds SDNC images from source code
function build_sdnc_images {
    local src_folder=$1

    build_docker_image $src_folder/installation/ubuntu
    asserts_image openecomp/ubuntu-sdnc-image

    /var/lib/dpkg/info/ca-certificates-java.postinst configure
    build_docker_image $src_folder/installation/sdnc
    asserts_image openecomp/sdnc-image

    build_docker_image $src_folder/installation/admportal
    asserts_image openecomp/admportal-sdnc-image

    build_docker_image $src_folder/installation/dgbuilder
    asserts_image openecomp/dgbuilder-sdnc-image
}

# install_sdnc() -  Download and install SDNC services from source code
function install_sdnc {
    install_package unzip
    local src_folder=/opt/openecomp/sdnc

    clone_all_sdnc_repos
    if [[ "$compile_repo" == "True" ]]; then
        compile_all_sdnc_repos
    fi

    if [[ "$build_image" == "True" ]]; then
        build_sdnc_images $src_folder/oam
    else
        pull_openecomp_image sdnc-image openecomp/sdnc-image:latest
        pull_openecomp_image admportal-sdnc-image openecomp/admportal-sdnc-image:latest
        pull_openecomp_image dgbuilder-sdnc-image openecomp/dgbuilder-sdnc-image:latest
    fi
    pushd $src_folder/oam/installation/src/main/yaml
    install_docker_compose
    /opt/docker/docker-compose up -d
    popd
}

# init_sdnc() - Function that initialize SDNC services
function init_sdnc {
    install_ODL
    start_ODL
    install_sdnc
}
