#!/bin/bash

set -o xtrace

# install_sdnc() -  Download and install SDNC services from source code
function install_sdnc {
    export MTU=$(/sbin/ifconfig | grep MTU | sed 's/.*MTU://' | sed 's/ .*//' | sort -n | head -1)
    local src_folder=/opt/sdnc/oam
    clone_repo sdnc/oam /opt/sdnc/oam
    pushd $src_folder/installation/src/main/yaml
    install_docker_compose
    /opt/docker/docker-compose up -d
    popd
}

# init_sdnc() - Function that initialize SDNC services
function init_sdnc {
    pull_openecomp_image sdnc-image openecomp/sdnc-image:latest
    pull_openecomp_image admportal-sdnc-image openecomp/admportal-sdnc-image:latest
    pull_openecomp_image dgbuilder-sdnc-image openecomp/dgbuilder-sdnc-image:latest
    install_sdnc
}
